#!python

#!/usr/bin/env python3
import os
import math
import Bio

SAMPLES = set()
sample_dict = {}

SAMPLES = config["samples"].split(",")
RAW_DIR = "raw/"
TRIMMED_DIR = "trimmed/"
MAPPED_DIR = "mapped/"

rule all:
    input:
        expand(f"{MAPPED_DIR}{{sample}}.fastq sample=SAMPLES)

rule trim_reads:
    input:
        f"{RAW_DIR}{{sample}}.fastq"
    output:
        f"{TRIMMED_DIR}{{sample}}_trimmed.fastq"
    conda:
        "envs/trimgalore.yaml"
    shell:
        "echo 'trimming {input}' > {output}; trim_galore {input} --quality 20 --fastqc --length 20 --output_dir {output}"
        
        
        
