#!python

#!/usr/bin/env python3
import os
import math

SAMPLES = set()
sample_dict = {}

SAMPLES = config["samples"].split(",")
gtf_file = config["gff_path"]
model_path = config["model_path"]
DESEQ_OUTPUT = config["deseq_output"]
INPUT_DATA = "profiles/"
EXON_FILE = config["exons"]
ECLIP_PATH = config["eclip"]
RUN_TYPE = config["run_type"].lower()
RUN_VERSION = 2 if RUN_TYPE == "3utr" else 3
COVERAGE = "coverage/"
TARGET = "targets/"
TARGET_OUTPUT = "targets/output/"
TARGET_OUTPUT_5utr = "targets/output_5utr/"
TARGET_OUTPUT_3utr = "targets/output_3utr/"
OUTPUT_PDF = "pdf/"
version = "_90_20"

if RUN_VERSION == 2:
    TARGET_FOLDER_OUTPUT = TARGET_OUTPUT_3utr
else:
    TARGET_FOLDER_OUTPUT = TARGET_OUTPUT_5utr
    
    

rule all:
    input:
        expand(f"{TARGET}{{sample}}.combination_summary.txt", sample=SAMPLES),
        expand(f"{TARGET}{{sample}}.varna_summary.txt", sample=SAMPLES),
        expand(f"{OUTPUT_PDF}{{sample}}.pdf_summary.txt", sample=SAMPLES),
        

rule combine_information:
    input:
        input_dms = lambda wildcards: f"{INPUT_DATA}{wildcards.sample}/{wildcards.sample}.dms_coverage{version}.txt",
    output:
        output_summary = f"{TARGET}{{sample}}.combination_summary.txt",
    conda:
        "envs/rnafold.yaml"
    shell:
        """
        mkdir -p {TARGET_OUTPUT}
        mkdir -p {TARGET_OUTPUT_5utr}
        mkdir -p {TARGET_OUTPUT_3utr}

        python Integration/scripts/combine_information_{RUN_TYPE}.py \
            --dms_analysis_file {input.input_dms} \
            --target_folder {TARGET_OUTPUT} \
            --oops_seq_folder {DESEQ_OUTPUT} \
            --summary {output.output_summary} \
            --exon_file {EXON_FILE} \
            --gff_path {gtf_file} \
            --target_folder_5utr {TARGET_OUTPUT_5utr} \
            --target_folder_3utr {TARGET_OUTPUT_3utr} \
            --model_path {model_path} \
            --eclip_path {ECLIP_PATH}
        """
        


rule run_varna:
    input:
        summary = lambda wildcards: f"{TARGET}{{sample}}.combination_summary.txt",
    output:
        output_file = f"{TARGET}{{sample}}.varna_summary.txt",
    conda:
        "envs/java.yaml"
    shell:
        """
        mkdir -p {TARGET_OUTPUT}
        
        python Integration/scripts/run_varna.py \
            --target_folder {TARGET_FOLDER_OUTPUT} \
            --output_summary {output.output_file} \
            --version {RUN_VERSION}
        """


rule create_pdf:
    input:
        summary = lambda wildcards: f"{TARGET}{{sample}}.varna_summary.txt",
        input_dms = lambda wildcards: f"{INPUT_DATA}{wildcards.sample}/{wildcards.sample}.dms_coverage{version}.txt",
    output:
        output_pdf = f"{OUTPUT_PDF}{{sample}}.pdf_summary.txt",
    conda:
        "envs/pil.yaml"
    shell:
        """
        mkdir -p {OUTPUT_PDF}
        
        python Integration/scripts/create_pdf.py \
            --output_folder {TARGET_FOLDER_OUTPUT} \
            --dms_analysis_file {input.input_dms} \
            --output_pdf {output.output_pdf} \
            --pdf_folder {OUTPUT_PDF} \
            --run_type {RUN_TYPE}
            
        """
        


